#!/sbin/sh

# Script made by Noxxxious
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

BOOT="boot.img"

# Move boot.img to AIK folder
mv -f /tmp/"$BOOT" /tmp/aik/boot.img

# mount AIK folder & start unpacking
cd /tmp/aik
chmod 777 unpackimg.sh;
./unpackimg.sh boot.img
rm -f boot.img

# Now lets repack to get this magic working
chmod 777 repackimg.sh;
./repackimg.sh

# move & rename created image to tmp folder so updater-script will pick up
mv -f /tmp/aik/image-new.img /tmp/boot.img
cd /tmp

# append Samsung enforcing tag to prevent warning at boot (taken from Lazyflasher @ credits to Jcadduano)
echo -n "SEANDROIDENFORCE" >> boot.img
